# Generated by Django 5.1.3 on 2025-01-22 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Recipient Name",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="chats/%Y/%m/%d",
                        verbose_name="Recipient image",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Last message created",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("group", "group"), ("direct", "direct")],
                        default="direct",
                        max_length=10,
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="char_author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chat Author",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="chat_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Chat members",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chats",
                "ordering": ("-created",),
            },
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "message_text",
                    models.TextField(
                        blank=True, max_length=1000, null=True, verbose_name="Message"
                    ),
                ),
                (
                    "content",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="messages/%Y/%m/%d",
                        verbose_name="File",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "image"),
                            ("doc", "doc"),
                            ("video", "video"),
                            ("text", "text"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="messages/thumbnails/%Y/%m/%d",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Content duration",
                    ),
                ),
                (
                    "content_size",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Content size",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, verbose_name="Is hidden message"
                    ),
                ),
                (
                    "chat_obj",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message",
                        to="chat_app.chat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_sender",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Sender",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ("-created",),
            },
            bases=("core.basemodel",),
        ),
        migrations.CreateModel(
            name="MessageReceiverDetail",
            fields=[
                (
                    "basemodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.basemodel",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Is read message"),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        default=False, verbose_name="Is hidden message"
                    ),
                ),
                (
                    "message_obj",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_message",
                        to="chat_app.message",
                        verbose_name="Receiver message detail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_receiver",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Receiver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Receiver",
                "verbose_name_plural": "Message Receivers",
                "ordering": ("-created",),
            },
            bases=("core.basemodel",),
        ),
    ]
