# Generated by Django 5.1.3 on 2025-01-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="topic",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="type",
            field=models.CharField(
                choices=[
                    ("back end", "Back End"),
                    ("cache", "Cache"),
                    ("data base", "Db"),
                    ("async", "Async"),
                    ("general", "General"),
                    ("other", "Other"),
                ],
                default="back end",
            ),
        ),
    ]
