# Generated by Django 5.1.3 on 2024-11-15 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("is_for_kids_allowed", models.BooleanField(default=False)),
                ("is_for_adult_only", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TravelPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                ("date_start", models.DateTimeField(blank=True, null=True)),
                ("date_finish", models.DateTimeField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("impression", models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                "verbose_name": "TravelPlan",
                "verbose_name_plural": "TravelPlans",
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "description",
                    models.TextField(blank=True, max_length=250, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Film", "Film"), ("Serial", "Serial")], default="Film"
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="rest_app.genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
            },
        ),
    ]
