# Generated by Django 5.1.3 on 2024-11-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genre",
            name="is_for_adult_only",
        ),
        migrations.RemoveField(
            model_name="genre",
            name="is_for_kids_allowed",
        ),
        migrations.AddField(
            model_name="movie",
            name="is_for_adult_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="movie",
            name="is_for_kids_allowed",
            field=models.BooleanField(default=False),
        ),
    ]
