# Generated by Django 5.1.3 on 2024-11-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_app", "0002_remove_genre_is_for_adult_only_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="genre",
        ),
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.ManyToManyField(blank=True, null=True, to="rest_app.genre"),
        ),
    ]
