# Generated by Django 5.1.3 on 2024-11-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_app", "0003_remove_movie_genre_movie_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="genre",
            field=models.ManyToManyField(
                related_name="genre_of_movie", to="rest_app.genre"
            ),
        ),
    ]
