# Generated by Django 5.1.3 on 2025-01-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="fruits",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="recipe", to="recipes_app.fruit"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="meat",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="recipe", to="recipes_app.meat"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="sauce",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="recipe", to="recipes_app.sauce"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="vegetables",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="recipe", to="recipes_app.vegetable"
            ),
        ),
    ]
