# Generated by Django 5.1.3 on 2025-01-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes_app", "0002_alter_recipe_fruits_alter_recipe_meat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
